### ISSUE TITLE
og:imageの参照画像が agently.terass.com と違う

### ISSUE THREAD

**Issue by genk1** [terass-inc/tera-two-lp#7]
あえてであれば無視してください

現状のテラスの og:image
<img width="438" alt="Screen Shot 0002-07-16 at 16 48 21" src="https://user-images.githubusercontent.com/8629766/87642367-60b05200-c784-11ea-9845-4909b720459c.png">

joinagentlyのog:image
<img width="457" alt="Screen Shot 0002-07-16 at 16 50 07" src="https://user-images.githubusercontent.com/8629766/87642419-76be1280-c784-11ea-91aa-77d4c97c11df.png">

**Comment by yasuhiro-y** [comment]
はい、緑色のやつが古いです
